### ISSUE TITLE
Removing Dotenv

### ISSUE THREAD

**Issue by janko** [lipanski/slow-down#7]
Hello 👋 

First of all, thank you for creating this gem! I'm interested in using it, but I noticed that for some reason it loads `dotenv` and runs `Dotenv.load`. This makes me uneasy, because we don't use `dotenv`, we instead have custom logic that loads our `.env` file. I feel like activating `dotenv` shouldn't be the responsibility of this gem.

**Comment by lipanski** [comment]
hi @janko 

fixed with https://github.com/lipanski/slow-down/pull/8 and release as 0.3.1

sorry for the late reply, I completely missed the notification for this issue.

**Comment by janko** [comment]
No problem, thank you for the fix!
