### ISSUE TITLE
Is 0.x version ready for production?

### ISSUE THREAD

**Issue by delphaber** [lipanski/slow-down#9]
Hi!

Just wondering if 0.x version is suitable for production use. Do you use in production? :)

Thanks for the code!

**Comment by lipanski** [comment]
@delphaber yes, I have used it in production successfully for a couple of years at a decent load. the project is a bit stale right now: I haven't been using it in a while so I don't actively add new features or upgrade dependencies unless requested or if someone opens a PR. the concept underneath is fairly simple so I don't see anything that could break though. PRs / issues are welcome and I'll try to review them in a timely manner. if you have any questions, let me know.

**Comment by delphaber** [comment]
hi @lipanski thanks for the reply. Yeah, I saw the code and all it's clear!

I don't think that gems need to be constantly updated, if they works in production and are mature enough :) I was just curious about the `0.x` versioning and wanted to check if it was production ready! :)

I'll open a PR to add ruby 2.6 and 2.7 to travis
